"""
Django settings for dpunk project.

Generated by 'django-admin startproject' using Django 1.9a1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*fw&ga!iq^$mrn#bfx#xq-q2w31001@vveyz1uu$dk&$5jrp$a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = [True, False][0]

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'pagination',
    'easy_timezones',

    'apps.users',
    'apps.posts',
    'apps.tests',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'apps.users.middleware.UserMiddleware',

    'pagination.middleware.PaginationMiddleware',
    'easy_timezones.middleware.EasyTimezoneMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.tz',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'core.global.site',
            ],
            'builtins' : [
                'pagination.templatetags.pagination_tags',

                'core.templatetags.core',
            ]
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = ['en-us', 'ru'][1]

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL, MEDIA_URL = '/static/', '/media/'
STATIC_ROOT, MEDIA_ROOT = os.path.join(BASE_DIR, 'static'), os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'users.User'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

SITE_NAME   = u'dpunk'
SITE_DOMAIN = u'127.0.0.1:8000'
SITE_EMAIL  = u'dpunkru@mail.ru'

from django.core.urlresolvers import reverse_lazy
LOGIN_URL = reverse_lazy('user_login')

GEOIP_DATABASE = 'GeoLiteCity.dat'

import django.db.models.options as options
options.DEFAULT_NAMES = options.DEFAULT_NAMES + ('verbose_name_rod',)