# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-17 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата присоединения')),
                ('is_activated', models.BooleanField(default=False, help_text='Указывает, что пользователь подтвердил свой e-mail.', verbose_name='E-mail подтверждён')),
                ('is_staff', models.BooleanField(default=False, help_text='Указывает, что пользователь имеет доступ к панели администратора.', verbose_name='Статус персонала')),
                ('is_active', models.BooleanField(default=True, help_text='Указывает, что пользователь активен. Используйте вместо удаления аккаунта.', verbose_name='Активен')),
                ('activation_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='Код активации')),
                ('reset_password_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='Код сброса пароля')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
    ]
