# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-11-06 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Чё тестируем?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='Ссылка')),
                ('state', models.TextField(verbose_name='Состояние')),
                ('anonymous', models.TextField(verbose_name='Аноним')),
                ('not_activated', models.TextField(verbose_name='Не активированный')),
                ('activated', models.TextField(verbose_name='Активированный')),
                ('not_active', models.TextField(verbose_name='Удалённый')),
                ('not_moderated', models.TextField(verbose_name='Заблокированный')),
                ('staff', models.TextField(verbose_name='Админ')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
