# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-11-06 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='activated',
            field=models.TextField(blank=True, null=True, verbose_name='Активированный'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='anonymous',
            field=models.TextField(blank=True, null=True, verbose_name='Аноним'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='not_activated',
            field=models.TextField(blank=True, null=True, verbose_name='Не активированный'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='not_active',
            field=models.TextField(blank=True, null=True, verbose_name='Удалённый'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='not_moderated',
            field=models.TextField(blank=True, null=True, verbose_name='Заблокированный'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='staff',
            field=models.TextField(blank=True, null=True, verbose_name='Админ'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='state',
            field=models.TextField(blank=True, null=True, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
