# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-11-06 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20151107_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='state',
        ),
        migrations.AddField(
            model_name='testcase',
            name='case',
            field=models.TextField(blank=True, null=True, verbose_name='Случай'),
        ),
    ]
