# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-18 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20151018_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anons',
            field=models.TextField(help_text='Будет отображаться как в ленте материалов в качестве анонса, так и на странице материала в качестве вступления', verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, help_text='Будет отображаться только на странице материала', null=True, verbose_name='Текст'),
        ),
    ]
